[package]
name = "ruizukun-dev/t"
description = "A Runtime Typechecker for Roblox"
version = "3.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["lib", "lib/init.lua", "default.project.json", "LICENSE", "README.md", "wally.toml"]

[dependencies]
